"""源码 Bot 的 zip 加固校验、入口解析与构建配方。

分层：本模块只做纯校验与命令拼装（0 Docker 依赖，单测友好）；
容器执行由 bots/manager 在上传 admission 内经 docker supervisor 的
构建通道完成，产物沿用既有 ELF 分类、版本冻结与完整性链。
"""
from __future__ import annotations

import posixpath
import zipfile
from dataclasses import dataclass

from bzplat.backend.runtime.limits import (
    BOT_BUILD_TIMEOUT_SEC,
    BUILDER_IMAGE,
    SOURCE_MAX_FILES,
    SOURCE_MAX_UNCOMPRESSED_BYTES,
)

ZIP_MAGIC = b"PK\x03\x04"

# 每种语言的默认入口与候选序（zip 内以 POSIX 相对路径声明）。
DEFAULT_ENTRIES: dict[str, tuple[str, ...]] = {
    "c": ("main.c",),
    "cpp": ("main.cpp", "main.cc", "main.cxx"),
    "go": ("main.go",),
    "python": ("__main__.py", "main.py"),
}

# 构建命令模板：/src 只读挂载源码，/out 收产物；网络禁用由容器统一保证。
# C/C++ 静态链接避免运行镜像与构建镜像的 glibc 版本漂移。
_BUILD_COMMANDS: dict[str, str] = {
    "c": (
        "gcc -O2 -static -D_BOTZONE_ONLINE=1 -DBOTARENA_ONLINE=1 "
        "-o /out/bot /src/{entry}"
    ),
    "cpp": (
        "g++ -O2 -static -D_BOTZONE_ONLINE=1 -DBOTARENA_ONLINE=1 "
        "-o /out/bot /src/{entry}"
    ),
    "go": (
        # /src 只读：复制到 /tmp 可写目录再生成常量文件与编译，
        # 同时使多文件 package（go build .）可用。
        "cp -r /src /tmp/src && "
        "cat > /tmp/src/botarena_online.go <<'GO'\n"
        "// Code generated by the platform build step.\n"
        "package main\n"
        "const BotArenaOnline = true\n"
        "GO\n"
        "cd /tmp/src && "
        "GOCACHE=/tmp/gocache GOPATH=/tmp/gopath "
        "go build -o /out/bot ."
    ),
}


class SourceBuildError(Exception):
    def __init__(self, code: str, message: str) -> None:
        super().__init__(message)
        self.code = code
        self.message = message


@dataclass
class SourceSpec:
    language: str  # 'c' | 'cpp' | 'go' | 'python'
    entry: str  # zip 内 POSIX 相对入口路径
    files: int
    uncompressed_bytes: int


def validate_source_language(language: object) -> str:
    lang = str(language or "").strip().lower()
    if lang not in DEFAULT_ENTRIES:
        raise SourceBuildError(
            "unsupported_source_language",
            "源码语言仅支持 c / cpp / go / python",
        )
    return lang


def _safe_member_name(name: str) -> bool:
    """拒绝绝对路径、.. 穿越、反斜杠与控制字符；强制 POSIX 相对路径。

    目录项（尾斜杠）先归一化再比较；Info-ZIP / Windows / macOS Finder
    生成的 zip 普遍携带目录项，不应作为不安全路径拒绝。
    """
    name = name.rstrip("/")
    if not name or "\\" in name or name.startswith("/"):
        return False
    if any(ord(ch) < 32 or ord(ch) == 127 for ch in name):
        return False
    normalized = posixpath.normpath(name)
    if normalized.startswith("..") or normalized in (".", "/"):
        return False
    return normalized == name


def inspect_source_zip(path, *, language: str, declared_entry: object = None) -> SourceSpec:
    """解压前完整校验 zip 结构并解析入口；不做任何解压写入。

    防 zip 炸弹与路径穿越：文件数、未压缩总量、成员名逐条校验；
    符号链接/加密成员直接拒绝。
    """
    lang = validate_source_language(language)
    try:
        archive = zipfile.ZipFile(path)
    except zipfile.BadZipFile as exc:
        raise SourceBuildError(
            "invalid_source_zip", "源码包不是有效的 zip 文件"
        ) from exc
    with archive:
        infos = archive.infolist()
        if not infos:
            raise SourceBuildError("invalid_source_zip", "源码包为空")
        if len(infos) > SOURCE_MAX_FILES:
            raise SourceBuildError(
                "invalid_source_zip",
                f"源码包文件数超过 {SOURCE_MAX_FILES}",
            )
        total = 0
        names: list[str] = []
        for info in infos:
            if not _safe_member_name(info.filename):
                raise SourceBuildError(
                    "invalid_source_zip",
                    f"源码包含不安全路径: {info.filename[:80]}",
                )
            if (
                info.create_system == 3
                and (info.external_attr >> 16) & 0o170000 == 0o120000
            ):
                raise SourceBuildError(
                    "invalid_source_zip", "源码包不允许符号链接"
                )
            if info.flag_bits & 0x1:
                raise SourceBuildError(
                    "invalid_source_zip", "源码包不允许加密成员"
                )
            total += int(info.file_size)
            if total > SOURCE_MAX_UNCOMPRESSED_BYTES:
                raise SourceBuildError(
                    "invalid_source_zip",
                    "源码包解压后总量超出上限",
                )
            if not info.is_dir():
                names.append(info.filename)

        if declared_entry:
            entry = str(declared_entry).strip()
            if not _safe_member_name(entry):
                raise SourceBuildError("invalid_entry", "入口路径不合法")
            if entry not in names:
                raise SourceBuildError(
                    "invalid_entry", f"入口文件不在源码包内: {entry}"
                )
        else:
            entry = ""
            for candidate in DEFAULT_ENTRIES[lang]:
                if candidate in names:
                    entry = candidate
                    break
            if not entry:
                raise SourceBuildError(
                    "invalid_entry",
                    "未声明入口且找不到默认入口（"
                    + " / ".join(DEFAULT_ENTRIES[lang])
                    + "）",
                )
        return SourceSpec(
            language=lang,
            entry=entry,
            files=len(names),
            uncompressed_bytes=total,
        )


def build_recipe(spec: SourceSpec) -> dict:
    """冻结进 bot_versions.build_recipe_json 的构建配方（可审计、可复现）。"""
    if spec.language == "python":
        return {
            "kind": "python-bundle",
            "entry": spec.entry,
            "timeout_sec": BOT_BUILD_TIMEOUT_SEC,
        }
    return {
        "kind": "compile",
        "language": spec.language,
        "entry": spec.entry,
        "image": BUILDER_IMAGE,
        "command": _BUILD_COMMANDS[spec.language].format(entry=spec.entry),
        "timeout_sec": BOT_BUILD_TIMEOUT_SEC,
        "defines": ["_BOTZONE_ONLINE=1", "BOTARENA_ONLINE=1"],
    }


def build_command(recipe: dict) -> str:
    """由冻结配方重建容器内命令；配方缺失/漂移即拒绝。"""
    if recipe.get("kind") != "compile":
        raise SourceBuildError("invalid_recipe", "构建配方不是 compile 类型")
    command = recipe.get("command")
    if not isinstance(command, str) or not command:
        raise SourceBuildError("invalid_recipe", "构建配方缺少命令")
    return command
